spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        password: rohit
        url: jdbc:mariadb://localhost:3306/loan_db
        username: rohit
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true



